### ISSUE TITLE
script.py giving segmentation fault

### ISSUE THREAD

**Issue by rishikaul22** [xlincw0w/Cure_Clustering_Algorithm#5]
hey

i tried running script.py but it gives segmentation fault

![image](https://user-images.githubusercontent.com/54001108/133057379-e3b12bef-edc7-473e-a66d-b50ad3b9b3bd.png)

**Comment by xlincw0w** [comment]
Hey @rishikaul22,

first of all make sure you are using python3 and not python2,
also have you installed dependencies packages using your favorite package manager (pip or conda) ?

**Comment by rishikaul22** [comment]
I’m running python3 only
Could you list the dependencies in a requirements.txt file?
